/**
 * Generates the canonical ANEMIASCAN_SCREENING_COMMITMENT_V1 golden vector.
 *
 * Solidity is the ground truth here — it is what actually runs on-chain — so
 * this script deploys AnemiaRegistry to an ephemeral in-memory Hardhat
 * network, calls its pure `hashScreeningCommitment`, and writes the fixed
 * inputs plus the resulting hash to sdk/golden-vector.json. The Python and
 * TypeScript replicas (backend/tests/test_commitment.py,
 * sdk/ts/verify.mjs) then re-derive the same hash from the same literal
 * field values via their own abi.encode + keccak256 and must match exactly.
 *
 * Run with: npm run vector   (network: hardhat, in-memory, no funds needed)
 */
import fs from "fs";
import path from "path";
import { ethers } from "hardhat";

async function main() {
  const [admin] = await ethers.getSigners();
  const Factory = await ethers.getContractFactory("AnemiaRegistry");
  const registry = await Factory.deploy(admin.address);
  await registry.waitForDeployment();

  const schemaHash = await registry.SCHEMA_HASH();

  const fields = {
    scanIdHash: ethers.keccak256(ethers.toUtf8Bytes("golden-vector-scan-id")),
    imageDigest: ethers.keccak256(ethers.toUtf8Bytes("golden-vector-image")),
    modelHash: ethers.keccak256(ethers.toUtf8Bytes("golden-vector-model")),
    riskCode: 2,
    recommendationCode: 1,
    confidenceBps: 9321,
    qualityBps: 8800,
    consentHash: ethers.keccak256(ethers.toUtf8Bytes("golden-vector-consent")),
    capturedAt: 1760000000,
    salt: ethers.keccak256(ethers.toUtf8Bytes("golden-vector-salt")),
  };

  const commitment = await registry.hashScreeningCommitment(
    fields.scanIdHash,
    fields.imageDigest,
    fields.modelHash,
    fields.riskCode,
    fields.recommendationCode,
    fields.confidenceBps,
    fields.qualityBps,
    fields.consentHash,
    fields.capturedAt,
    fields.salt,
  );

  const vector = {
    _comment:
      "Ground truth generated by contracts/scripts/printCommitmentVector.ts via AnemiaRegistry.hashScreeningCommitment on an ephemeral Hardhat network. Do not hand-edit. Regenerate with `npm run vector` in contracts/ after any change to the commitment encoding.",
    schemaTag: "ANEMIASCAN_SCREENING_COMMITMENT_V1",
    schemaHash,
    fields,
    expectedCommitment: commitment,
  };

  const outPath = path.join(__dirname, "..", "..", "sdk", "golden-vector.json");
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, JSON.stringify(vector, null, 2) + "\n");

  console.log("schemaHash:", schemaHash);
  console.log("expectedCommitment:", commitment);
  console.log("written to:", outPath);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
