import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import type { ScanAnalysis, PatientProfile } from './types'
import { formatDateTime } from './format'

export function generatePatientReportPDF(analysis: ScanAnalysis, patient?: PatientProfile) {
  const doc = new jsPDF()

  // Add branding/header
  doc.setFontSize(22)
  doc.setTextColor(0, 0, 0)
  doc.text('AnemiaScan Report', 14, 22)

  doc.setFontSize(12)
  doc.setTextColor(100)
  doc.text(`Generated on: ${formatDateTime(Date.now())}`, 14, 30)

  // Add Patient Details
  doc.setFontSize(16)
  doc.setTextColor(0, 0, 0)
  doc.text('Patient Information', 14, 45)
  
  if (patient) {
    autoTable(doc, {
      startY: 50,
      head: [['Field', 'Details']],
      body: [
        ['Name', patient.name],
        ['Age', patient.age.toString()],
        ['Gender', patient.gender],
        ['Medical Notes', patient.medicalNotes || 'None provided'],
      ],
      theme: 'grid',
      headStyles: { fillColor: [41, 128, 185] },
    })
  } else {
    doc.setFontSize(12)
    doc.text('No patient profile attached.', 14, 52)
  }

  // Add Scan Results
  const finalY = (doc as any).lastAutoTable ? (doc as any).lastAutoTable.finalY : 60

  doc.setFontSize(16)
  doc.setTextColor(0, 0, 0)
  doc.text('Screening Analysis', 14, finalY + 15)

  autoTable(doc, {
    startY: finalY + 20,
    head: [['Metric', 'Value']],
    body: [
      ['Risk Score', `${analysis.riskScore}/100 (${analysis.riskLevel})`],
      ['Confidence', `${analysis.confidence}/100`],
      ['Est. Hemoglobin Range', `${analysis.hbRange.low.toFixed(1)} - ${analysis.hbRange.high.toFixed(1)} g/dL`],
    ],
    theme: 'grid',
    headStyles: { fillColor: [46, 204, 113] },
  })

  // Add Signals Breakdown
  const finalY2 = (doc as any).lastAutoTable.finalY

  doc.setFontSize(16)
  doc.text('Signal Breakdown', 14, finalY2 + 15)

  const signalsData = analysis.signals.map(s => [
    s.label, 
    `${s.value}/100`, 
    `${Math.round(s.weight * 100)}%`,
    s.hint
  ])

  autoTable(doc, {
    startY: finalY2 + 20,
    head: [['Signal', 'Value', 'Weight', 'Explanation']],
    body: signalsData,
    theme: 'striped',
    styles: { cellWidth: 'wrap' },
    columnStyles: {
      3: { cellWidth: 80 }
    }
  })

  // Disclaimer footer
  doc.setFontSize(10)
  doc.setTextColor(150, 150, 150)
  const pageHeight = doc.internal.pageSize.height
  doc.text('DISCLAIMER: This report is a screening aid generated by an AI heuristic on a photograph.', 14, pageHeight - 20)
  doc.text('It is NOT a clinical diagnosis and cannot replace a laboratory hemoglobin (CBC) blood test.', 14, pageHeight - 15)

  // Save PDF
  const filename = patient ? `${patient.name.replace(/\s+/g, '_')}_ScanReport.pdf` : 'AnemiaScan_Report.pdf'
  doc.save(filename)
}
