import { useState } from 'react'
import { ArrowLeft, CheckCircle2, ClipboardList, Clock3, Stethoscope } from 'lucide-react'
import { Button } from '@/components/ui/button'
import type { DoctorReport } from '@/src/lib/types'

export function DoctorPortal({ reports, onBack, onSaveAdvice }: { reports: DoctorReport[]; onBack: () => void; onSaveAdvice: (id: string, advice: string) => void }) {
  const [selectedId, setSelectedId] = useState(reports[0]?.id ?? '')
  const selected = reports.find((report) => report.id === selectedId) ?? reports[0]
  const awaiting = reports.filter((report) => report.status === 'Awaiting Review').length

  return <div className="min-h-dvh bg-muted/30"><header className="border-b border-border bg-background"><div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-4"><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center bg-primary text-primary-foreground"><Stethoscope className="h-5 w-5" /></div><div><p className="font-semibold">AnemiaScan Doctor Portal</p><p className="text-xs text-muted-foreground">Clinical review workspace</p></div></div><Button variant="outline" size="sm" onClick={onBack}><ArrowLeft className="mr-2 h-4 w-4" /> Patient experience</Button></div></header><main className="mx-auto max-w-6xl px-6 py-8"><h1 className="text-3xl font-semibold tracking-tight">Review patient screenings</h1><p className="mt-2 max-w-2xl text-sm leading-relaxed text-muted-foreground">Review AI-assisted screening results and add clinician guidance. This is not a diagnostic or prescribing tool.</p><div className="my-7 grid gap-3 sm:grid-cols-3"><Metric icon={<ClipboardList />} label="Reports received" value={reports.length} /><Metric icon={<Clock3 />} label="Awaiting review" value={awaiting} /><Metric icon={<CheckCircle2 />} label="Reviewed" value={reports.length - awaiting} /></div><div className="grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><section className="border border-border bg-background"><div className="border-b border-border p-5"><h2 className="font-semibold">Review queue</h2></div>{reports.length ? reports.map((report) => <button key={report.id} type="button" onClick={() => setSelectedId(report.id)} className={`block w-full border-b border-border p-5 text-left ${selected?.id === report.id ? 'bg-primary/5' : 'hover:bg-muted/50'}`}><div className="flex justify-between gap-3"><span className="font-medium">{report.patientLabel}</span><span className="text-xs text-muted-foreground">{report.status}</span></div><p className="mt-2 text-sm text-muted-foreground">{report.analysis.riskLevel} · {report.analysis.riskScore}%</p></button>) : <p className="p-6 text-sm text-muted-foreground">No patient reports yet.</p>}</section>{selected ? <ReportDetail report={selected} onSave={onSaveAdvice} /> : <section className="flex min-h-64 items-center justify-center border border-dashed border-border bg-background p-8 text-center text-sm text-muted-foreground">Send a completed patient scan here for review.</section>}</div></main></div>
}

function Metric({ icon, label, value }: { icon: React.ReactNode; label: string; value: number }) { return <div className="border border-border bg-background p-4"><div className="flex h-9 w-9 items-center justify-center bg-primary/10 text-primary">{icon}</div><p className="mt-4 text-sm text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-semibold">{value}</p></div> }

function ReportDetail({ report, onSave }: { report: DoctorReport; onSave: (id: string, advice: string) => void }) { const [advice, setAdvice] = useState(report.doctorAdvice ?? ''); return <section className="border border-border bg-background p-6"><p className="text-sm font-medium text-primary">Selected report</p><h2 className="mt-1 text-2xl font-semibold">{report.patientLabel}</h2><div className="mt-6 grid gap-4 sm:grid-cols-3"><Info label="Risk level" value={report.analysis.riskLevel} /><Info label="Risk score" value={`${report.analysis.riskScore}%`} /><Info label="Brightness" value={`${Math.round(report.analysis.brightness)}/255`} /></div>{report.analysis.imageDataUrl && <img src={report.analysis.imageDataUrl} alt="Patient-contributed lower eyelid scan" className="mt-6 aspect-video w-full object-cover" />}<label className="mt-6 block text-sm font-medium">Clinician guidance<textarea value={advice} onChange={(event) => setAdvice(event.target.value)} rows={5} placeholder="Add guidance for this patient..." className="mt-2 w-full border border-input bg-background p-3 text-sm outline-none focus:border-primary" /></label><Button className="mt-4 rounded-none" onClick={() => onSave(report.id, advice)}>Save guidance</Button><p className="mt-4 text-xs leading-relaxed text-muted-foreground">AI-assisted screening only. Clinical confirmation may be required.</p></section> }
function Info({ label, value }: { label: string; value: string }) { return <div><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-semibold">{value}</p></div> }
